"""Fill the memo, evaluation page, and README measured blocks from harness JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CA = HERE / "criterion_agreement" / "results"
LLM = HERE / "llm_cost" / "results"
ROC = HERE / "rules_only_coverage" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _md(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    ca = _read(CA / "results.json")
    llm = _read(LLM / "results.json")
    roc = _read(ROC / "results.json")
    ca_md = _md(CA / "results.md")
    llm_md = _md(LLM / "results.md")
    roc_md = _md(ROC / "results.md")

    ca_lines = ca_md.splitlines()
    ca_start = next(i for i, line in enumerate(ca_lines) if line.startswith("| code |"))
    ca_table = "\n".join(ca_lines[ca_start:])
    llm_table = "\n".join(line for line in llm_md.splitlines() if line.startswith("|"))
    roc_conf = roc_md.split("## Confusion matrix")[-1].strip()
    ship = ", ".join(ca["ship_default_only"]) or "(none)"
    vcep = ", ".join(ca["needs_vcep_overlay"]) or "(none)"
    ca_decision = f"Ship default-only for {ship}. Require a VCEP overlay before shipping {vcep}."
    cost_lines = [
        f"- Mean input tokens / literature prompt: "
        f"{llm['models'][0]['mean_input_tokens_per_prompt']:.1f}",
        f"- Input tokens / variant (3 nodes): "
        f"{llm['models'][0]['input_tokens_per_variant_3_nodes']:.1f}",
        f"- Cheapest / variant: {llm['decision']}",
        f"- Local tokenize time: {llm['local_render_and_tokenize_seconds'] * 1000:.2f} ms "
        f"({llm['local_ms_per_excerpt']:.2f} ms/excerpt)",
        "- API RTT: unmeasured",
        "- Rules-path CPU on 100 variants: unmeasured as a separate timer "
        "(runs inside criterion_agreement; wall time is dominated by process startup)",
    ]
    filled = (
        template.replace("{{LLM_N}}", str(llm["n_excerpts"]))
        .replace("{{LLM_TABLE}}", llm_table)
        .replace("{{LLM_DECISION}}", str(llm["decision"]))
        .replace("{{LLM_LOCAL_MS}}", f"{llm['local_render_and_tokenize_seconds'] * 1000:.2f}")
        .replace("{{CA_N}}", str(ca["n_variants"]))
        .replace("{{CA_TABLE}}", ca_table)
        .replace("{{CA_DECISION}}", ca_decision)
        .replace("{{ROC_ACCURACY}}", f"{roc['rules_only_concordance']:.3f}")
        .replace(
            "{{ROC_SUMMARY}}",
            f"Rules-only concordance = {roc['n_correct']}/{roc['n_variants']} "
            f"= {roc['rules_only_concordance']:.3f}. "
            f"Zero-LLM code fraction = {roc['zero_llm_fraction']:.3f} "
            f"({roc['n_rules']}+{roc['n_catalog']}/28).",
        )
        .replace("{{ROC_CONFUSION}}", roc_conf)
        .replace("{{COST_MODEL}}", "\n".join(cost_lines))
    )
    return filled


def render_eval() -> str:
    ca = _md(CA / "results.md")
    roc = _md(ROC / "results.md")
    llm = _md(LLM / "results.md")
    roc_json = _read(ROC / "results.json")
    p3_path = ROOT / "research" / "phase3" / "results" / "results.md"
    p3 = _md(p3_path) if p3_path.exists() else ""
    return (
        "# Evaluation (Phases 0–3)\n\n"
        "Regenerated by `make eval` / `make research`. "
        "The rules-only concordance is the published baseline. "
        "Expert-panel hold-out numbers do not exist yet.\n\n"
        f"Baseline (rules-only) concordance: **{roc_json['rules_only_concordance']:.3f}** "
        f"({roc_json['n_correct']}/{roc_json['n_variants']}).\n\n"
        f"{p3}\n\n{ca}\n\n{roc}\n\n{llm}\n"
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme(memo_already_written: bool = True) -> None:
    readme_path = ROOT / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    roc = _read(ROC / "results.json")
    ca = _read(CA / "results.json")
    p3_path = ROOT / "research" / "phase3" / "results" / "results.json"
    if p3_path.exists():
        p3 = _read(p3_path)
        freq = f"{p3['frequency_only_concordance']:.3f}"
        llm_on = f"{p3['full_llm_on_concordance']:.3f}"
        llm_off = f"{p3['full_llm_off_concordance']:.3f}"
        freq_n = str(p3["n_variants"])
        on_n = str(p3["n_variants"])
        off_n = str(p3["n_variants"])
    else:
        freq, llm_on, llm_off = "Phase 3", "Phase 3", "Phase 3"
        freq_n = on_n = off_n = "—"
    body = (
        "| System | Concordance | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Rules-only baseline (Phase 0) | {roc['rules_only_concordance']:.3f} | "
        f"{roc['n_variants']} | Default 2015 computational codes + combining table |\n"
        f"| Frequency-threshold-only | {freq} | {freq_n} | BA1/BS1/PM2 only |\n"
        f"| Full system (LLM on) | {llm_on} | {on_n} | Typed graph; literature cache-only |\n"
        f"| Full system (LLM off) | {llm_off} | {off_n} | Must equal rules-only |\n\n"
        f"Default-only codes that cleared F1≥0.90 with no strength mismatch: "
        f"{', '.join(ca['ship_default_only']) or '(none)'}. "
        f"Codes blocked on a VCEP overlay: "
        f"{', '.join(ca['needs_vcep_overlay']) or '(none)'}."
    )
    text = _replace_block(text, "<!-- EVAL_TABLE_BEGIN -->", "<!-- EVAL_TABLE_END -->", body)
    readme_path.write_text(text, encoding="utf-8")
    del memo_already_written


def main() -> None:
    memo = render_memo()
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(memo, encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    if (ROOT / "README.md").exists():
        patch_readme()
    print("wrote docs/phase-0/research-memo.md, docs/EVALUATION.md, README results block")


if __name__ == "__main__":
    main()
